export const SETBOOKS = 'SETBOOKS';
export const PLUSMINUSBOOK = 'PLUSMINUSBOOK';
export const ADDBOOKTOTEMPCART = 'ADDBOOKTOTEMPCART';
export const ADDBOOKTOCART = 'ADDBOOKTOCART';
export const DELETEBOOKFROMCART = 'DELETEBOOKFROMCART';
export const SETINFO = 'SETINFO';
export const SETLOGIN = 'SETLOGIN';
export const CLEARCART = 'CLEARCART';
